#!/bin/bash

#启动elasticsearch
elasticsearch --cluster.name Goblin --node.name Neptune > ~/tmp/elk/elasticsearch.log &

sleep 5

# 启动logstash
logstash -f ~/tmp/elk/logstash-1.conf > ~/tmp/elk/logstash.log &

sleep 5

# 启动kibana
/home/david/opt/kibana-4.4.0-linux-x64/bin/kibana > ~/tmp/elk/kibana.log &

sleep 5

echo "访问 http://localhost:5601"
