#!/bin/bash
sudo /etc/rc.d/rc.oracle-xe start
lsnrctl start

# result=$(sqlplus -s "/ as sysdba" <<EOF
# set heading off;
# startup;
# EOF
# )
# echo $result

result=$(sqlplus -s "/ as sysdba" <<EOF
set heading off;
shutdown immediate;
startup;
EOF
)
echo $result
