#!/bin/bash
# $1 启动文件 ; $2 frame名
if [ -z $1 ] || [ -z $2 ] ; then
    echo "exit"
    exit 0
fi

isActive=$(ps -ef|grep $1 | grep -v grep | wc -l)

if [ $isActive == 2 ]
then
  $1
else
  wmctrl -a "$2"
fi
