#!/bin/sh
if test -z "$1"
then
    ~/opt/apache-tomcat-6.0.35/bin/startup.sh &&  tail -f ~/opt/apache-tomcat-6.0.35/logs/catalina.out
else
    ps -ef|  grep opt/apac | awk '{print $2}' | head -n 1 | xargs -n1 kill -9
fi
