#!/bin/bash

sudo ifconfig wlan0 up
sudo wpa_supplicant -B -i wlan0 -Dwext -c /etc/wpa_supplicant.conf
sudo wpa_cli -i wlan0 add_network
sudo wpa_cli -i wlan0 set_network 0 ssid "pangmei"
sudo wpa_cli -i wlan0 set_network 0 psk "88128829"
sudo wpa_cli -i wlan0 select_network 0
sudo wpa_cli -i wlan0 enable_network 0
sudo dhclient wlan0
